# The imperative front door to a declarative Homebrew (#35).
#
# `nix-homebrew.mutableTaps = false` makes /opt/homebrew/Library/Taps a symlink
# into the store, so `brew tap` cannot write there — it fails with "could not
# create leading directories". The answer is not to make the directory writable
# (that costs HOMEBREW_NO_AUTO_UPDATE and turns a symlink flip into a 75 MiB
# rsync on every activation) but to move where the *pin* is written: this script
# records it in the repo and rebuilds, so an imperative `brew tap` ends up
# declarative.
#
# Two generated files, both pure data, both rewritten wholesale from JSON so
# nothing here ever does regex surgery on a hand-written file:
#
#   modules/homebrew/taps.nix          taps, pinned to a rev + hash
#   hosts/<host>/homebrew-generated.nix   brews and casks
#
# Both are `git add`ed, and that is not a nicety: flake evaluation only sees
# files git knows about, so an untracked generated file is invisible and the tap
# silently does not exist. Staged-but-uncommitted is the resting place — it
# shows up in `git diff --staged` for review and nothing is committed for you.
#
# Installed as `nix-brew`; modules/homebrew/default.nix wraps it in a `brew`
# shell function so muscle memory keeps working. `command brew` is the bypass.

REPO="${NIXOS_CONFIG_DIR:-$HOME/.config/nixos-config}"
LEDGER="${XDG_STATE_HOME:-$HOME/.local/state}/nix-brew/scratch.json"

RED=$'\033[1;31m'
GREEN=$'\033[1;32m'
YELLOW=$'\033[1;33m'
NC=$'\033[0m'

die() { echo "${RED}error:${NC} $*" >&2; exit 1; }
note() { echo "${GREEN}nix-brew:${NC} $*" >&2; }
warn() { echo "${YELLOW}nix-brew:${NC} $*" >&2; }

# `nix` itself is deliberately not pinned — the one on PATH is the Determinate
# install, same call the other scripts in this repo make.
nix_() { nix --extra-experimental-features 'nix-command flakes' "$@"; }

usage() {
  cat >&2 <<'EOF'
nix-brew — record Homebrew changes in the nix config instead of only on disk

  nix-brew tap <user/repo> [--no-switch]     pin a tap and rebuild
  nix-brew tap --bump [<user/repo>]          re-resolve pinned taps to HEAD
  nix-brew untap <user/repo> [--no-switch]   drop a pinned tap and rebuild
  nix-brew install [--cask] [-p|-s] <name>…  install, then choose how to record
  nix-brew uninstall [--cask] <name>…        uninstall, offer to undeclare
  nix-brew drift                             list installed-but-not-declared

  -p, --permanent   record in the repo (no prompt)
  -s, --scratch     install without declaring, but log it for `drift`
      --switch      rebuild now (install only; tap/untap always rebuild)
      --no-switch   record only, do not rebuild

Anything else is passed straight through to `brew`.
Set NIXOS_CONFIG_DIR to point at a checkout other than ~/.config/nixos-config.
EOF
  exit 2
}

# macOS does not promise a stable case for the short hostname, and the flake
# attribute is the (case-sensitive) directory name under hosts/. Same fix-up as
# apps/build-switch.sh — see the long comment there for why it is unconditional.
resolve_host() {
  local want lower candidate
  want="$(hostname -s)"
  lower="$(echo "$want" | tr '[:upper:]' '[:lower:]')"
  for candidate in "$REPO"/hosts/*/; do
    candidate="$(basename "$candidate")"
    if [ "$(echo "$candidate" | tr '[:upper:]' '[:lower:]')" = "$lower" ]; then
      echo "$candidate"; return
    fi
  done
  echo "$want"
}

HOST="$(resolve_host)"
TAPS_FILE="$REPO/modules/homebrew/taps.nix"
GEN_FILE="$REPO/hosts/$HOST/homebrew-generated.nix"

# `brew tap` names a tap `user/repo`; on disk and in nix-homebrew's attrset it is
# `user/homebrew-repo`. Normalise once, here, so the rest of the script only
# deals in the directory form.
tap_key() {
  local t="$1"
  [[ "$t" == */* ]] || die "not a tap name: $t (want user/repo)"
  local owner="${t%%/*}" repo="${t#*/}"
  [[ "$repo" == homebrew-* ]] || repo="homebrew-$repo"
  echo "${owner}/${repo}"
}

read_taps() {
  if [ -f "$TAPS_FILE" ]; then nix_ eval --json --file "$TAPS_FILE"; else echo '{}'; fi
}

write_taps() {
  local json="$1" body
  body="$(jq -r '
    to_entries | sort_by(.key) | map(
      "  \(.key|tojson) = {\n" +
      "    owner = \(.value.owner|tojson);\n" +
      "    repo = \(.value.repo|tojson);\n" +
      "    rev = \(.value.rev|tojson);\n" +
      "    hash = \(.value.hash|tojson);\n" +
      "  };"
    ) | join("\n")' <<<"$json")"
  {
    echo "# GENERATED by \`brew tap\` (#35). Do not edit by hand."
    echo "#"
    echo "# One entry per tap added imperatively, pinned to the revision it was tapped"
    echo "# at. flake.nix maps these over \`fetchFromGitHub\` and merges the result into"
    echo "# \`extraTaps\`, so they are cloned from the store exactly like the hand-written"
    echo "# taps and inherit the same \`trusted: true\` treatment."
    echo "#"
    echo "# \`rev\` is frozen and nix-homebrew sets HOMEBREW_NO_AUTO_UPDATE=1, so nothing"
    echo "# here moves on its own. \`brew tap --bump\` re-resolves HEAD."
    echo "{"
    if [ -n "$body" ]; then echo "$body"; fi
    echo "}"
  } > "$TAPS_FILE"
  git -C "$REPO" add "$TAPS_FILE"
}

read_gen() {
  if [ -f "$GEN_FILE" ]; then
    nix_ eval --json --file "$GEN_FILE"
  else
    echo '{"brews":[],"casks":[]}'
  fi
}

write_gen() {
  local json="$1"
  mkdir -p "$(dirname "$GEN_FILE")"
  {
    echo "# GENERATED by \`brew install\` (#35). Do not edit by hand."
    echo "#"
    echo "# \`mine.homebrew.brews\` / \`.casks\` are list options, so what is declared here"
    echo "# merges with the hand-written lists in default.nix — nothing has to edit that"
    echo "# file, and this one can be rewritten wholesale. flake.nix imports it only when"
    echo "# it exists, so a host without one needs no ceremony."
    echo "{"
    jq -r '
      def nixlist: if length == 0 then "[ ]" else
        "[\n" + (sort | unique | map("    " + tojson) | join("\n")) + "\n  ]" end;
      "  brews = \(.brews | nixlist);\n  casks = \(.casks | nixlist);"' <<<"$json"
    echo "}"
  } > "$GEN_FILE"
  git -C "$REPO" add "$GEN_FILE"
}

do_switch() {
  note "rebuilding ${HOST}…"
  ( cd "$REPO" && nix_ run ".#build-switch" -- "$HOST" )
}

# The declared set, straight from the Brewfile nix-darwin renders. That option is
# the Brewfile *text*, so there is no store path to hunt for, and it is the
# post-merge truth: it includes casks contributed by modules, not just the host
# lists.
declared() {
  local kind="$1"
  ( cd "$REPO" && nix_ eval --raw ".#darwinConfigurations.${HOST}.config.homebrew.brewfile" 2>/dev/null ) \
    | sed -n "s/^${kind} \"\([^\"]*\)\".*/\1/p" | sort
}

# `brew leaves` prints a formula from a third-party tap fully qualified
# (openfga/openfga/fga) while the Brewfile declares it unqualified (fga, which
# works because the tap is trusted). Compare on the bare name or every tapped
# formula reads as drift.
bare_names() { sed 's|.*/||' | sort -u; }

ledger_add() {
  local name="$1"
  mkdir -p "$(dirname "$LEDGER")"
  [ -f "$LEDGER" ] || echo '{}' > "$LEDGER"
  local tmp; tmp="$(mktemp)"
  jq --arg n "$name" --arg at "$(date -u +%Y-%m-%dT%H:%M:%SZ)" \
    '.[$n] = { at: $at }' "$LEDGER" > "$tmp" && mv "$tmp" "$LEDGER"
}

cmd_tap() {
  local bump=0 switch=1 target=""
  for arg in "$@"; do
    case "$arg" in
      --bump) bump=1 ;;
      --no-switch) switch=0 ;;
      -*) die "unknown flag for tap: $arg" ;;
      *) target="$arg" ;;
    esac
  done

  local taps; taps="$(read_taps)"

  if [ "$bump" -eq 1 ]; then
    local keys
    if [ -n "$target" ]; then keys="$(tap_key "$target")"
    else keys="$(jq -r 'keys[]' <<<"$taps")"; fi
    [ -n "$keys" ] || die "nothing pinned to bump"
    while read -r key; do
      [ -n "$key" ] || continue
      local owner repo pin
      owner="$(jq -r --arg k "$key" '.[$k].owner' <<<"$taps")"
      repo="$(jq -r --arg k "$key" '.[$k].repo' <<<"$taps")"
      pin="$(nix_ flake prefetch --json "github:${owner}/${repo}")"
      taps="$(jq --arg k "$key" --argjson p "$pin" \
        '.[$k].rev = $p.locked.rev | .[$k].hash = $p.hash' <<<"$taps")"
      note "bumped ${key} to $(jq -r '.locked.rev[0:12]' <<<"$pin")"
    done <<<"$keys"
    write_taps "$taps"
    if [ "$switch" -eq 1 ]; then do_switch; fi
    return
  fi

  [ -n "$target" ] || usage
  local key owner repo pin
  key="$(tap_key "$target")"
  owner="${key%%/*}"; repo="${key#*/}"

  if jq -e --arg k "$key" 'has($k)' <<<"$taps" >/dev/null; then
    warn "${key} is already pinned; use --bump to move it to HEAD"
    return
  fi

  note "resolving github:${owner}/${repo}…"
  # One call gets both the rev and an SRI hash, and fetchFromGitHub on those
  # lands on the identical store path — no nix-prefetch-git, no conversion.
  pin="$(nix_ flake prefetch --json "github:${owner}/${repo}")" \
    || die "cannot fetch github:${owner}/${repo}"

  taps="$(jq --arg k "$key" --arg o "$owner" --arg r "$repo" --argjson p "$pin" \
    '.[$k] = { owner: $o, repo: $r, rev: $p.locked.rev, hash: $p.hash }' <<<"$taps")"
  write_taps "$taps"
  note "pinned ${key} at $(jq -r '.locked.rev[0:12]' <<<"$pin")"

  # A tap is only usable once it is in the store-linked Taps directory, so
  # unlike install this has to rebuild before the formulae exist.
  if [ "$switch" -eq 1 ]; then
    do_switch
  else
    warn "not switched; run build-switch to make the tap usable"
  fi
}

cmd_untap() {
  local switch=1 target=""
  for arg in "$@"; do
    case "$arg" in
      --no-switch) switch=0 ;;
      -*) die "unknown flag for untap: $arg" ;;
      *) target="$arg" ;;
    esac
  done
  [ -n "$target" ] || usage

  local key taps; key="$(tap_key "$target")"; taps="$(read_taps)"
  jq -e --arg k "$key" 'has($k)' <<<"$taps" >/dev/null \
    || die "${key} is not pinned here (hand-written taps live in flake.nix)"

  write_taps "$(jq --arg k "$key" 'del(.[$k])' <<<"$taps")"
  note "unpinned ${key}"
  if [ "$switch" -eq 1 ]; then do_switch; fi
}

# Ask once, and only when there is a terminal to ask on: a wrapper that blocks on
# stdin would deadlock any script that calls `brew`.
ask_disposition() {
  if [ ! -t 0 ] || [ ! -r /dev/tty ]; then echo scratch; return; fi
  local reply
  while true; do
    printf '%s' "${YELLOW}record in the config?${NC} [p]ermanent / [s]cratch / [c]ancel: " >/dev/tty
    read -r reply </dev/tty || { echo cancel; return; }
    case "$reply" in
      p|P|permanent) echo permanent; return ;;
      s|S|scratch) echo scratch; return ;;
      c|C|cancel|"") echo cancel; return ;;
    esac
  done
}

cmd_install() {
  local kind=brew disposition="" switch=0
  local -a names=()
  for arg in "$@"; do
    case "$arg" in
      --cask|--casks) kind=cask ;;
      -p|--permanent) disposition=permanent ;;
      -s|--scratch) disposition=scratch ;;
      --switch) switch=1 ;;
      -*) die "unknown flag for install: $arg" ;;
      *) names+=("$arg") ;;
    esac
  done
  [ "${#names[@]}" -gt 0 ] || usage

  [ -n "$disposition" ] || disposition="$(ask_disposition)"
  if [ "$disposition" = cancel ]; then note "cancelled"; return; fi

  # Install first: fast feedback, and a declaration for something that does not
  # build is worse than no declaration. The next activation is idempotent.
  if [ "$kind" = cask ]; then
    command brew install --cask "${names[@]}"
  else
    command brew install "${names[@]}"
  fi

  if [ "$disposition" = scratch ]; then
    for n in "${names[@]}"; do ledger_add "$n"; done
    warn "not declared. It is still installed globally and nothing will remove it —"
    warn "\`brew drift\` lists it. For something genuinely temporary, use \`nix shell nixpkgs#…\`."
    return
  fi

  local gen recorded=0 already; gen="$(read_gen)"
  already="$(declared "$kind" | bare_names)"
  for n in "${names[@]}"; do
    # Already in the host's hand-written list, or pulled in by a module that
    # needs it. Recording it again would put the same name in two places, which
    # is how a list starts lying about who owns an entry.
    if grep -qx "${n##*/}" <<<"$already"; then
      warn "$n is already declared; leaving it where it is"
      continue
    fi
    gen="$(jq --arg n "$n" --arg k "${kind}s" '.[$k] += [$n]' <<<"$gen")"
    recorded=1
  done
  if [ "$recorded" -eq 0 ]; then return; fi
  write_gen "$gen"
  note "declared in hosts/${HOST}/homebrew-generated.nix (staged, not committed)"
  if [ "$switch" -eq 1 ]; then do_switch; fi
}

cmd_uninstall() {
  local kind=brew
  local -a names=()
  for arg in "$@"; do
    case "$arg" in
      --cask|--casks) kind=cask ;;
      -*) die "unknown flag for uninstall: $arg" ;;
      *) names+=("$arg") ;;
    esac
  done
  [ "${#names[@]}" -gt 0 ] || usage

  if [ "$kind" = cask ]; then
    command brew uninstall --cask "${names[@]}"
  else
    command brew uninstall "${names[@]}"
  fi

  # Uninstalling something that is still declared is a no-op with extra steps:
  # the next activation puts it straight back.
  local gen changed=0; gen="$(read_gen)"
  for n in "${names[@]}"; do
    if jq -e --arg n "$n" --arg k "${kind}s" 'any(.[$k][]; . == $n)' <<<"$gen" >/dev/null; then
      gen="$(jq --arg n "$n" --arg k "${kind}s" '.[$k] -= [$n]' <<<"$gen")"
      changed=1
      note "undeclared $n"
    elif declared "$kind" | bare_names | grep -qx "${n##*/}"; then
      warn "$n is declared by hand (host default.nix or a module) — the next"
      warn "activation will reinstall it. Remove it there if you meant that."
    fi
  done
  if [ "$changed" -eq 1 ]; then write_gen "$gen"; fi
  return 0
}

cmd_drift() {
  local installed
  echo "${YELLOW}formulae installed but not declared${NC}"
  installed="$(command brew leaves | bare_names)"
  comm -23 <(echo "$installed") <(declared brew) | while read -r n; do
    [ -n "$n" ] || continue
    local at; at="$(jq -r --arg n "$n" '.[$n].at // "—"' "$LEDGER" 2>/dev/null || echo "—")"
    printf '  %-30s scratch since %s\n' "$n" "$at"
  done
  echo "${YELLOW}casks installed but not declared${NC}"
  installed="$(command brew list --cask -1 | bare_names)"
  comm -23 <(echo "$installed") <(declared cask) | sed 's/^/  /'
}

[ -d "$REPO/.git" ] || die "no checkout at $REPO (set NIXOS_CONFIG_DIR)"

case "${1:-}" in
  tap) shift; cmd_tap "$@" ;;
  untap) shift; cmd_untap "$@" ;;
  install) shift; cmd_install "$@" ;;
  uninstall) shift; cmd_uninstall "$@" ;;
  drift) shift; cmd_drift "$@" ;;
  ""|-h|--help|help) usage ;;
  *) command brew "$@" ;;
esac
