# GENERATED by `brew tap` (#35). Do not edit by hand.
#
# One entry per tap added imperatively, pinned to the revision it was tapped
# at. flake.nix maps these over `fetchFromGitHub` and merges the result into
# `extraTaps`, so they are cloned from the store exactly like the hand-written
# taps and inherit the same `trusted: true` treatment.
#
# `rev` is frozen and nix-homebrew sets HOMEBREW_NO_AUTO_UPDATE=1, so nothing
# here moves on its own. `brew tap --bump` re-resolves HEAD.
{
}
