# GENERATED by `brew tap` (#35). Do not edit by hand.
#
# One entry per tap added imperatively, pinned to the revision it was tapped
# at. flake.nix maps these over `fetchFromGitHub` and merges the result into
# `extraTaps`, so they are cloned from the store exactly like the hand-written
# taps and inherit the same `trusted: true` treatment.
#
# `rev` is frozen and nix-homebrew sets HOMEBREW_NO_AUTO_UPDATE=1, so nothing
# here moves on its own. `brew tap --bump` re-resolves HEAD.
{
  "superd22/homebrew-macos-steam" = {
    owner = "superd22";
    repo = "homebrew-macos-steam";
    rev = "17ec99db67097826a02c3ef5c6eee6410fc4adbb";
    hash = "sha256-IinYgvogQ4nvPVPI75W97uM+B1JwnHNOpDWxDcOUqi8=";
  };
}
