# GENERATED by `brew install` (#35). Do not edit by hand.
#
# `mine.homebrew.brews` / `.casks` are list options, so what is declared here
# merges with the hand-written lists in default.nix — nothing has to edit that
# file, and this one can be rewritten wholesale. flake.nix imports it only when
# it exists, so a host without one needs no ceremony.
{
  brews = [
    "macos-steam-shim"
  ];
  casks = [
    "crossover"
  ];
}
