# WeMaintain's cloud environments (#8): AWS SSO profiles, the RDS IAM database
# helpers, the DataGrip datasources for the same databases, and the Pritunl VPN
# (#32).
#
# Everything a WeMaintain developer needs to reach the cloud from a fresh Mac,
# behind one flag. Turn on `mine.work.wemaintain.enable`, build-switch, run
# `wm-login`, and `withPg <anything>` works. No copying ~/.aws from the old
# machine, and no VPN profile carried over either: it is minted per Mac from
# the server, and the old machine's is revoked when that machine is retired.
#
# This is a nix-darwin module, for the same reason modules/programs/datagrip is:
# it owns system packages (the CLIs), a cask, files in the home directory
# (~/.aws), and a pre-activation fix-up for a work-installed tool, and all of
# those belong to the same "I work at WeMaintain" switch.
#
#
# A CONSUMER OF THE SHARED DEVENV REPO (#43)
#
# The facts and most of the machinery are WeMaintain's, not this config's, and
# live in the `wm` flake input (wemaintain/devenv), which every WeMaintain repo
# also imports. One copy, two readers; see its docs/adr/0005.
#
#   from wm                           here
#   -------                           ----
#   lib.data: accounts, profiles,     the ~/.aws/config renderer (upstream only
#     databases, MCP servers,           renders one into a devenv shell's
#     the SSO portal, the VPN url       AWS_CONFIG_FILE; DataGrip reads this one)
#   lib.mkRdsHelpers: withPg & co.    which databases get a helper, and its name
#   lib.rdsCaBundle                   the DataGrip mapping and its labels
#                                     `wm-login`, the Pritunl cask, /etc/zshenv
#
# gcloud is gone from here entirely: the data repo, the only one near BigQuery,
# gets the SDK, the project and both logins from wm's gcloud module, as
# environment variables rather than an activation script that could fail.
#
# `mine.work.wemaintain.databases` is still declared once and feeds both the
# helpers and DataGrip, so a host override (`databases.staging.user = ...`)
# moves both tools at once. Before #8 they were two hand-copied lists and they
# disagreed about staging (backend_dev + prod:back in the shell, wmadmin +
# prod:sudo in DataGrip).
#
#
# NOTHING SECRET
#
# The whole module is endpoints, account ids, role names and a public CA
# bundle. The credentials are SSO tokens `aws sso login` puts in ~/.aws/sso and
# RDS IAM tokens minted per connection. None of that is in the store or in this
# repo.
{ config, lib, pkgs, wm, ... }:

let
  cfg = config.mine.work.wemaintain;

  # The organisation's facts, declared once in the shared devenv repo and read
  # by both it and this config. Everything below is still `mkDefault`, so a
  # host overrides one field exactly as it did when these were literals here.
  # See wm's docs/adr/0005-one-declaration-two-consumers.md.
  data = wm.lib.data;
  user = config.mine.user.name;

  # ~/.aws/config, in the "legacy" SSO layout (sso_start_url on every profile
  # rather than a shared [sso-session]). It is what `aws sso login` with no
  # profile, DataGrip's AWS toolkit and the CLI all agree on, and one login
  # covers every profile with the same start URL.
  #
  # Rendered here because wm's aws module only renders one into a devenv
  # shell's AWS_CONFIG_FILE, and DataGrip and the helpers outside a repo read
  # this file instead.
  awsConfig =
    let
      a = cfg.aws;
      profileIni = name: p: ''
        [profile ${name}]
        sso_start_url = ${a.ssoStartUrl}
        sso_region = ${a.ssoRegion}
        sso_account_id = ${a.accounts.${p.account}}
        sso_role_name = ${p.role}
        region = ${a.region}
        output = json
      '';
    in
    ''
      # Generated by modules/work/wemaintain. Edits here are overwritten on the
      # next `nix run .#build-switch`; change the nix config instead.

      [default]
      sso_start_url = ${a.ssoStartUrl}
      sso_registration_scopes = sso:account:access
      sso_region = ${a.ssoRegion}

    '' + lib.concatStringsSep "\n" (lib.mapAttrsToList profileIni a.profiles);

  # The same executables a WeMaintain repo gets from wm's rds-shell module, fed
  # this module's `databases` rather than the shared ones so a host override
  # reaches them. Each mints a fresh RDS IAM token per call and execs its
  # arguments with DB_*, POSTGRES_* and PG* set; see wm's
  # modules/rds-shell/helpers.nix.
  #
  # Upstream names only staging and prod by default. prod-write gets its
  # helper because this config names it, loudly: `dangerWithPgProdWrite`.
  helperNames = lib.mapAttrs (_: db: db.shellFunction)
    (lib.filterAttrs (_: db: db.shellFunction != null) cfg.databases);

  rdsHelpers = wm.lib.mkRdsHelpers {
    inherit pkgs;
    names = helperNames;
    databases = cfg.databases;
  };

  # The interactive steps nix cannot do. AWS because the SSO token expires
  # after hours, Pritunl because minting a profile is a WeMaintain SSO login on
  # the server's own web UI. So this is both the one command to run on a new
  # Mac and what to run when `withPg` starts failing with an SSO error.
  #
  # The VPN step is the odd one out in being once-per-machine rather than
  # per-expiry: it is a no-op the moment a profile exists, so `wm-login` with no
  # argument stays the right thing to type either way (#32).
  #
  # gcloud's logins are no longer here: wm's gcloud module offers both on entry
  # to the data repo, which is the only place they are needed.
  wm-login = pkgs.writeShellApplication {
    name = "wm-login";
    runtimeInputs = [ pkgs.awscli2 ]
      ++ lib.optional cfg.vpn.enable pkgs.jq;
    text = ''
      what=''${1:-all}
      case "$what" in
        aws|${lib.optionalString cfg.vpn.enable "vpn|"}all) ;;
        *) echo "usage: wm-login [aws|${lib.optionalString cfg.vpn.enable "vpn|"}all]" >&2; exit 2 ;;
      esac

      ${lib.optionalString cfg.vpn.enable ''
        # The Pritunl CLI ships inside the cask's app bundle and is deliberately
        # not on PATH, so it is addressed by its full path.
        pritunl_client=/Applications/Pritunl.app/Contents/Resources/pritunl-client
        pritunl_profiles="$HOME/Library/Application Support/pritunl/profiles"

        vpn_profile() {
          if [ ! -x "$pritunl_client" ]; then
            echo "    Pritunl is not installed; run 'nix run .#build-switch' first." >&2
            return 1
          fi

          # `pritunl-client list` is NOT the check, despite being the obvious
          # one: on the electron client (1.3.4686) it prints an empty table even
          # with a profile added and a tunnel up, because it asks the service
          # rather than reading the app's own store. These files are that store.
          local existing
          existing=$(find "$pritunl_profiles" -maxdepth 1 -name '*.conf' 2>/dev/null | sort)
          if [ -n "$existing" ]; then
            echo "    a profile is already on this Mac, nothing to mint:"
            while IFS= read -r conf; do
              echo "      $(basename "$conf" .conf)  $(jq -r '"\(.organization) / \(.server) / \(.user)"' "$conf")"
            done <<< "$existing"
            # Only when asked for the VPN by name: as part of `wm-login all`,
            # run every time an SSO token expires, this would just be noise.
            if [ "$what" = vpn ]; then
              echo "    to replace it, delete it in the Pritunl app and run 'wm-login vpn' again."
            fi
            return 0
          fi

          echo "    log in with WeMaintain SSO, then either copy the profile link"
          echo "    or download the .tar. Opening the browser."
          /usr/bin/open ${lib.escapeShellArg cfg.vpn.url} || true

          # Both forms the server hands out are accepted verbatim:
          # `pritunl-client add [profile_uri|tar_path]`. A .tar that landed in
          # ~/Downloads while this was running is almost certainly the one, so
          # it is offered as the default rather than asking for a path to type.
          local recent="" answer=""
          recent=$(find "$HOME/Downloads" -maxdepth 1 -name '*.tar' -mmin -30 \
            -exec stat -f '%m %N' {} + 2>/dev/null | sort -rn | head -1 | cut -d' ' -f2-)

          echo
          if [ -n "$recent" ]; then
            read -r -p "    profile URI or .tar [$recent]: " answer || answer=""
            [ -n "$answer" ] || answer="$recent"
          else
            read -r -p "    profile URI or .tar: " answer || answer=""
          fi

          if [ -z "$answer" ]; then
            echo "    nothing given; run 'wm-login vpn' once you have the profile." >&2
            return 0
          fi

          if ! "$pritunl_client" add "$answer"; then
            echo "    'pritunl-client add' failed. Open Pritunl.app once so its" >&2
            echo "    service is running, then run 'wm-login vpn' again." >&2
            return 1
          fi
          echo "    added. Connect it from the Pritunl app."
        }
      ''}

      if [ "$what" = aws ] || [ "$what" = all ]; then
        # The [default] section of ~/.aws/config carries the SSO portal and
        # nothing else, so a login against it is a login for every profile.
        echo "==> AWS SSO (${cfg.aws.ssoStartUrl})"
        aws sso login
      fi

      ${lib.optionalString cfg.vpn.enable ''
        if [ "$what" = vpn ] || [ "$what" = all ]; then
          echo "==> Pritunl VPN (${cfg.vpn.url})"
          vpn_profile
        fi
      ''}
    '';
  };

  profileModule = { ... }: {
    options = {
      account = lib.mkOption {
        type = lib.types.str;
        example = "prod";
        description = "Key into `mine.work.wemaintain.aws.accounts`.";
      };
      role = lib.mkOption {
        type = lib.types.str;
        example = "BackendFullAccess";
        description = "The IAM Identity Center permission set, as `sso_role_name`.";
      };
    };
  };

  databaseModule = { name, ... }: {
    options = {
      host = lib.mkOption {
        type = lib.types.str;
        example = "wemaintain-pgsql-staging.cdtgkxemrw9j.eu-west-1.rds.amazonaws.com";
        description = "RDS endpoint.";
      };
      port = lib.mkOption {
        type = lib.types.port;
        default = 5432;
        description = "Port. Part of what the IAM token is minted for.";
      };
      database = lib.mkOption {
        type = lib.types.str;
        default = "postgres";
        description = "Database name, for the JDBC URL and for `PGDATABASE`.";
      };
      user = lib.mkOption {
        type = lib.types.str;
        example = "backend_dev";
        description = ''
          Database user. Must have `rds_iam` and be granted `rds-db:connect`
          to the role behind `awsProfile`; that pairing is the access level.
        '';
      };
      awsProfile = lib.mkOption {
        type = lib.types.str;
        example = "prod:back";
        description = ''
          Profile (a key of `mine.work.wemaintain.aws.profiles`) whose role
          mints the IAM token.
        '';
      };
      region = lib.mkOption {
        type = lib.types.str;
        default = cfg.aws.region;
        defaultText = lib.literalMD "`mine.work.wemaintain.aws.region`";
        description = "Region the token is minted in. Must match the endpoint's.";
      };
      shellFunction = lib.mkOption {
        type = lib.types.nullOr lib.types.str;
        default = null;
        example = "withPg";
        description = ''
          Name of the helper command to install for this database, or null for
          a DataGrip-only entry. `<name> <command>` runs the command with
          DB_*, POSTGRES_* and PG* set to a fresh IAM token. An executable
          from wm's `lib.mkRdsHelpers` since #43, not a zsh function, so it
          works from bash and scripts too; the option keeps its old name.
        '';
      };
      datagrip = {
        enable = lib.mkOption {
          type = lib.types.bool;
          default = true;
          description = ''
            Whether to declare a `mine.programs.datagrip.datasources` entry
            for this database. Only has an effect when
            `mine.programs.datagrip.enable` is on.
          '';
        };
        name = lib.mkOption {
          type = lib.types.str;
          default = "[${lib.toUpper name}] PG";
          defaultText = lib.literalMD "`\"[<NAME>] PG\"`";
          description = ''
            Datasource name in DataGrip. Its uuid, and so the IDE's local
            state for it, is derived from this, so keep it stable.
          '';
        };
      };
    };
  };
in
{
  # `mine.work.wemaintain.enable` is declared in modules/options.nix, with the
  # rest of the opt-in flags. Only the schema lives here.
  options.mine.work.wemaintain = {
    aws = {
      enable = lib.mkOption {
        type = lib.types.bool;
        default = true;
        description = "Manage ~/.aws/config, the RDS CA bundle and the `aws` CLI.";
      };

      ssoStartUrl = lib.mkOption {
        type = lib.types.str;
        default = data.aws.ssoStartUrl;
        defaultText = lib.literalExpression "wm.lib.data.aws.ssoStartUrl";
        description = "IAM Identity Center portal.";
      };

      ssoRegion = lib.mkOption {
        type = lib.types.str;
        default = data.aws.ssoRegion;
        defaultText = lib.literalExpression "wm.lib.data.aws.ssoRegion";
        description = "Region IAM Identity Center is deployed in.";
      };

      region = lib.mkOption {
        type = lib.types.str;
        default = data.aws.region;
        defaultText = lib.literalExpression "wm.lib.data.aws.region";
        description = "Default region for every profile, and for RDS tokens.";
      };

      accounts = lib.mkOption {
        type = lib.types.attrsOf lib.types.str;
        default = { };
        example = { prod = "123456789012"; };
        description = ''
          AWS account ids by short name. The organisation's accounts are
          declared by this module; a host adds to them.
        '';
      };

      profiles = lib.mkOption {
        type = lib.types.attrsOf (lib.types.submodule profileModule);
        default = { };
        example = { "prod:back" = { account = "prod"; role = "BackendFullAccess"; }; };
        description = ''
          Profiles written to ~/.aws/config, named as `--profile` takes them.
          The organisation's standard set is declared by this module; a host
          adds to it, or overrides a field with `lib.mkForce`.
        '';
      };
    };

    databases = lib.mkOption {
      type = lib.types.attrsOf (lib.types.submodule databaseModule);
      default = { };
      description = ''
        RDS databases reached over IAM auth. Each one becomes a helper command
        (when `shellFunction` is set) and a DataGrip datasource (when
        `datagrip.enable` is), from the one declaration. The standard ones
        are declared by this module; a host adds to them.
      '';
    };

    vpn = {
      enable = lib.mkOption {
        type = lib.types.bool;
        default = true;
        description = ''
          Install the Pritunl cask and give `wm-login` a `vpn` step that mints
          this Mac's VPN profile from the server below.
        '';
      };

      url = lib.mkOption {
        type = lib.types.str;
        default = data.vpn.url;
        defaultText = lib.literalExpression "wm.lib.data.vpn.url";
        description = ''
          The Pritunl server's login page, opened in the browser by
          `wm-login vpn`. It is behind WeMaintain SSO, which is why the profile
          cannot be minted from the CLI.
        '';
      };
    };
  };

  config = lib.mkIf cfg.enable {
    # The organisation, as it stands, from data/aws.nix. Every leaf is
    # `mkDefault` so a host can override one field without restating the rest,
    # and attribute sets merge, so adding a profile or a database is still one
    # entry in the host file.
    mine.work.wemaintain.aws.accounts = lib.mapAttrs (_: lib.mkDefault) data.aws.accounts;

    mine.work.wemaintain.aws.profiles = lib.mapAttrs
      (_: p: {
        account = lib.mkDefault p.account;
        role = lib.mkDefault p.role;
      })
      data.aws.profiles;

    # The endpoints come from data/databases.nix. Staging's lives in the prod
    # ACCOUNT, which is why its helper authenticates with a `prod:*` profile.
    #
    # The two fields below are deliberately NOT in the shared data: the helper
    # name and the DataGrip label are this config's choices about how to
    # present a database, not facts about one. The label especially, since
    # DataGrip derives a datasource's uuid from it and so owns local IDE state
    # that must stay stable here.
    #
    # staging and prod match the names wm's rds-shell gives them by default, so
    # `withPg` means the same thing inside a repo's shell and outside one.
    mine.work.wemaintain.databases =
      let
        presentation = {
          staging = { shellFunction = "withPg"; datagripName = "[STAGING] PG"; };
          prod = { shellFunction = "withPgProd"; datagripName = "[PROD] PG"; };
          prod-write = { shellFunction = "dangerWithPgProdWrite"; datagripName = "DANGER WRITE PG PROD"; };
        };
      in
      lib.mapAttrs
        (name: db:
          lib.mapAttrs (_: lib.mkDefault) db
          // lib.optionalAttrs (presentation ? ${name}) {
            shellFunction = lib.mkDefault presentation.${name}.shellFunction;
            datagrip.name = lib.mkDefault presentation.${name}.datagripName;
          })
        data.databases;

    # wm's data/check.nix already holds the shared data to these. They are here
    # for what a host adds or overrides on top of it.
    assertions =
      [
        {
          assertion = cfg.databases == { } || cfg.aws.enable;
          message = ''
            mine.work.wemaintain.databases needs mine.work.wemaintain.aws.enable:
            the helpers mint RDS IAM tokens with the `aws` CLI and the profiles
            this module writes.
          '';
        }
      ]
      ++ lib.mapAttrsToList
        (name: p: {
          assertion = cfg.aws.accounts ? ${p.account};
          message = ''
            mine.work.wemaintain.aws.profiles."${name}" refers to account
            "${p.account}", which is not in mine.work.wemaintain.aws.accounts.
          '';
        })
        cfg.aws.profiles
      ++ lib.mapAttrsToList
        (name: db: {
          assertion = cfg.aws.profiles ? ${db.awsProfile};
          message = ''
            mine.work.wemaintain.databases.${name} uses profile
            "${db.awsProfile}", which is not in mine.work.wemaintain.aws.profiles.
          '';
        })
        cfg.databases;

    # The CLIs are here rather than in modules/packages.nix because a fork that
    # does not work here has no use for them, and `wm-login` is the one
    # command to remember on a new machine.
    environment.systemPackages =
      [ wm-login ]
      ++ lib.optionals cfg.aws.enable [ pkgs.awscli2 ]
      ++ lib.optional (cfg.aws.enable && helperNames != { }) rdsHelpers;

    # The cask, not as a preference but as this module's implementation, the way
    # modules/desktop/betterdisplay declares its own: `wm-login vpn` runs a
    # binary inside /Applications/Pritunl.app. wm's vpn module drives the same
    # app on macOS and does not install it either (#32).
    homebrew.casks = lib.optional cfg.vpn.enable "pritunl";

    # DataGrip sees the same databases, if it is enabled at all. The datagrip
    # module ignores this when it is off, so nothing is gated here.
    mine.programs.datagrip.datasources = lib.mapAttrs'
      (_: db: lib.nameValuePair db.datagrip.name {
        driver = "postgresql";
        url = "jdbc:postgresql://${db.host}:${toString db.port}/${db.database}";
        userName = db.user;
        awsProfile = db.awsProfile;
        awsRegion = db.region;
      })
      (lib.filterAttrs (_: db: db.datagrip.enable) cfg.databases);

    # The MCP servers Claude Code talks to for work, merged into ~/.claude.json
    # by modules/programs/claude-code. From data/mcp.nix, in Claude Code's own
    # `mcpServers` shape, so nothing is translated on the way through.
    #
    # They are shared rather than sitting in that module's mcp-servers.json for
    # the same reason the Pritunl cask is here: a Looker instance at
    # wemaintain.cloud.looker.com and three Bedrock AgentCore gateways are
    # WeMaintain's, and a fork has no account for any of them. Endpoints only,
    # no credentials; Claude Code does OAuth against these and keeps the tokens
    # in the macOS keychain.
    #
    # The claude-code module ignores this when it is off, so nothing is gated.
    mine.programs.claude-code.extraMcpServers = data.mcp;

    # /etc/zshenv is fought over by two other tools:
    #   - tech.bastion.aiproxy (Bastion, the endpoint agent WeMaintain deploys)
    #     appends its HTTPS_PROXY / NODE_EXTRA_CA_CERTS exports
    #   - the Determinate installer prepends its "set up Nix on SSH" block
    # Either one replaces nix-darwin's symlink with a regular file, and etcChecks
    # then aborts the whole activation with "Unexpected files in /etc".
    #
    # Both tools also write to /etc/zshenv.local, which nix-darwin sources on
    # every shell and never manages, so the copy in /etc/zshenv is pure
    # duplication and nothing is lost by resetting it. Scoped to this one file
    # on purpose — a general /etc auto-heal would silently discard changes that
    # aren't mirrored anywhere. The .drifted copy is kept for inspection.
    #
    # preActivation runs before etcChecks (see nix-darwin's
    # activation-scripts.nix). This lived in hosts/common/darwin.nix until #8;
    # it is here because aiproxy is a work tool, not something every fork
    # of this repo has fighting over its /etc.
    system.activationScripts.preActivation.text = ''
      if [ -e /etc/zshenv ] && [ "$(readlink /etc/zshenv)" != "/etc/static/zshenv" ]; then
        echo "[nix-darwin] /etc/zshenv drifted, moving it to /etc/zshenv.drifted" >&2
        mv -f /etc/zshenv /etc/zshenv.drifted
      fi
    '';

    home-manager.users.${user} = lib.mkIf cfg.aws.enable {
      # Symlinks into the store, so `aws configure` cannot write them. That
      # is the point: the config is the declaration above. The SSO token
      # cache (~/.aws/sso) and CLI cache (~/.aws/cli) are untouched.
      home.file.".aws/config".text = awsConfig;

      # The helpers point at the bundle's store path and do not need this.
      # It stays for everything else that learned this path: backend's
      # manual-testing doc tells people to download the bundle here, and
      # scripts and .env files follow it.
      home.file.".aws/rds-ca-cert.pem".source = wm.lib.rdsCaBundle;
    };
  };
}
