# WeMaintain's cloud environments (#8): AWS SSO profiles, the RDS IAM database
# helpers, the DataGrip datasources for the same databases, gcloud, and the
# Pritunl VPN (#32).
#
# Everything a WeMaintain developer needs to reach the cloud from a fresh Mac,
# behind one flag. Turn on `mine.work.wemaintain.enable`, build-switch, run
# `wm-login`, and `withPg <anything>` works. No copying ~/.aws from the old
# machine, and no VPN profile carried over either: it is minted per Mac from
# the server, and the old machine's is revoked when that machine is retired.
#
# This is a nix-darwin module, for the same reason modules/programs/datagrip is:
# it owns system packages (the CLIs), a cask, files in the home directory
# (~/.aws), and a pre-activation fix-up for a work-installed tool, and all of
# those belong to the same "I work at WeMaintain" switch.
#
#
# SINGLE SOURCE OF TRUTH
#
# `mine.work.wemaintain.databases` is declared once and feeds two things:
#
#   - a shell function per database (`withPg`, `withPgProd`) that mints an RDS
#     IAM token with the right AWS profile and runs a command with the usual
#     DB_* / POSTGRES_* / PG* variables set, so `withPg pnpm start` and
#     `withPg psql` both just work;
#   - a DataGrip datasource per database, via `mine.programs.datagrip`, using
#     the same host, user and profile.
#
# Before #8 these were two hand-copied shell functions in modules/programs/zsh
# and a separate list of datasources in the host file, and they disagreed about
# staging (backend_dev + prod:back in the shell, wmadmin + prod:sudo in
# DataGrip). The shell's values are the ones encoded below: they are what the
# helpers used every day, while the DataGrip ones were a dump of whatever the
# IDE happened to hold. A host that wants the other can override one field.
#
#
# NOTHING SECRET
#
# The whole module is endpoints, account ids, role names and a public CA
# bundle. The credentials are SSO tokens `aws sso login` puts in ~/.aws/sso,
# RDS IAM tokens minted per connection, and whatever `gcloud auth login` keeps
# in ~/.config/gcloud. None of that is in the store or in this repo.
{ config, lib, pkgs, ... }:

let
  cfg = config.mine.work.wemaintain;
  user = config.mine.user.name;
  home = config.users.users.${user}.home;

  # ~/.aws/rds-ca-cert.pem used to be a manual prerequisite that the helpers
  # assumed existed (docs/new-machine.md). It is the RDS global CA bundle,
  # https://truststore.pki.rds.amazonaws.com/global/global-bundle.pem, vendored
  # rather than fetched so the build has no network dependency and the file
  # does not change under you when AWS adds a region. Byte-identical to the
  # copy that was on the machine this module was written on.
  rdsCaCert = "${home}/.aws/rds-ca-cert.pem";

  # ~/.aws/config, in the "legacy" SSO layout (sso_start_url on every profile
  # rather than a shared [sso-session]). It is what `aws sso login` with no
  # profile, DataGrip's AWS toolkit and the CLI all agree on, and one login
  # covers every profile with the same start URL.
  awsConfig =
    let
      a = cfg.aws;
      profileIni = name: p: ''
        [profile ${name}]
        sso_start_url = ${a.ssoStartUrl}
        sso_region = ${a.ssoRegion}
        sso_account_id = ${a.accounts.${p.account}}
        sso_role_name = ${p.role}
        region = ${a.region}
        output = json
      '';
    in
    ''
      # Generated by modules/work/wemaintain. Edits here are overwritten on the
      # next `nix run .#build-switch`; change the nix config instead.

      [default]
      sso_start_url = ${a.ssoStartUrl}
      sso_registration_scopes = sso:account:access
      sso_region = ${a.ssoRegion}

    '' + lib.concatStringsSep "\n" (lib.mapAttrsToList profileIni a.profiles);

  # One `with<Env>` function per database that asks for one. The token is
  # minted fresh on every call: RDS IAM tokens live 15 minutes, which is why
  # this is a function that wraps a command rather than an `export`.
  #
  # DB_* and POSTGRES_* are what the WeMaintain services read; PG* are libpq's
  # own, so `withPg psql` and `withPg pg_dump` need no further arguments
  # (psql itself is not installed by this module).
  shellFunction = db: ''
    ${db.shellFunction}() {
      if [ $# -eq 0 ]; then
        echo "usage: ${db.shellFunction} <command> [args...]  # ${db.user}@${db.host}" >&2
        return 1
      fi
      local host=${lib.escapeShellArg db.host}
      local user=${lib.escapeShellArg db.user}
      local password
      password=$(aws rds generate-db-auth-token \
        --profile ${lib.escapeShellArg db.awsProfile} \
        --hostname "$host" --port ${toString db.port} \
        --region ${lib.escapeShellArg db.region} \
        --username "$user") || return $?
      DB_HOST="$host" POSTGRES_HOST="$host" PGHOST="$host" \
      DB_PORT=${toString db.port} POSTGRES_PORT=${toString db.port} PGPORT=${toString db.port} \
      DB_USER="$user" POSTGRES_USERNAME="$user" PGUSER="$user" \
      DB_PASSWORD="$password" POSTGRES_PASSWORD="$password" PGPASSWORD="$password" \
      DB_SSL_CA=${lib.escapeShellArg rdsCaCert} PGSSLROOTCERT=${lib.escapeShellArg rdsCaCert} PGSSLMODE=verify-full \
      PGDATABASE=${lib.escapeShellArg db.database} \
      "$@"
    }
  '';

  shellDatabases = lib.filter (db: db.shellFunction != null) (lib.attrValues cfg.databases);

  # The one interactive step nix cannot do: the browser logins. Every one of
  # them is gated by a consent screen no CLI can drive — AWS and Google because
  # the SSO tokens expire (after hours and after days respectively), Pritunl
  # because minting a profile is a WeMaintain SSO login on the server's own web
  # UI. So this is both the one command to run on a new Mac and what to run
  # when `withPg` starts failing with an SSO error.
  #
  # The VPN step is the odd one out in being once-per-machine rather than
  # per-expiry: it is a no-op the moment a profile exists, so `wm-login` with no
  # argument stays the right thing to type either way (#32).
  wm-login = pkgs.writeShellApplication {
    name = "wm-login";
    runtimeInputs = [ pkgs.awscli2 ]
      ++ lib.optional cfg.gcp.enable pkgs.google-cloud-sdk
      ++ lib.optional cfg.vpn.enable pkgs.jq;
    text = ''
      what=''${1:-all}
      case "$what" in
        aws|gcp|${lib.optionalString cfg.vpn.enable "vpn|"}all) ;;
        *) echo "usage: wm-login [aws|gcp|${lib.optionalString cfg.vpn.enable "vpn|"}all]" >&2; exit 2 ;;
      esac

      ${lib.optionalString cfg.vpn.enable ''
        # The Pritunl CLI ships inside the cask's app bundle and is deliberately
        # not on PATH, so it is addressed by its full path.
        pritunl_client=/Applications/Pritunl.app/Contents/Resources/pritunl-client
        pritunl_profiles="$HOME/Library/Application Support/pritunl/profiles"

        vpn_profile() {
          if [ ! -x "$pritunl_client" ]; then
            echo "    Pritunl is not installed; run 'nix run .#build-switch' first." >&2
            return 1
          fi

          # `pritunl-client list` is NOT the check, despite being the obvious
          # one: on the electron client (1.3.4686) it prints an empty table even
          # with a profile added and a tunnel up, because it asks the service
          # rather than reading the app's own store. These files are that store.
          local existing
          existing=$(find "$pritunl_profiles" -maxdepth 1 -name '*.conf' 2>/dev/null | sort)
          if [ -n "$existing" ]; then
            echo "    a profile is already on this Mac, nothing to mint:"
            while IFS= read -r conf; do
              echo "      $(basename "$conf" .conf)  $(jq -r '"\(.organization) / \(.server) / \(.user)"' "$conf")"
            done <<< "$existing"
            # Only when asked for the VPN by name: as part of `wm-login all`,
            # run every time an SSO token expires, this would just be noise.
            if [ "$what" = vpn ]; then
              echo "    to replace it, delete it in the Pritunl app and run 'wm-login vpn' again."
            fi
            return 0
          fi

          echo "    log in with WeMaintain SSO, then either copy the profile link"
          echo "    or download the .tar. Opening the browser."
          /usr/bin/open ${lib.escapeShellArg cfg.vpn.url} || true

          # Both forms the server hands out are accepted verbatim:
          # `pritunl-client add [profile_uri|tar_path]`. A .tar that landed in
          # ~/Downloads while this was running is almost certainly the one, so
          # it is offered as the default rather than asking for a path to type.
          local recent="" answer=""
          recent=$(find "$HOME/Downloads" -maxdepth 1 -name '*.tar' -mmin -30 \
            -exec stat -f '%m %N' {} + 2>/dev/null | sort -rn | head -1 | cut -d' ' -f2-)

          echo
          if [ -n "$recent" ]; then
            read -r -p "    profile URI or .tar [$recent]: " answer || answer=""
            [ -n "$answer" ] || answer="$recent"
          else
            read -r -p "    profile URI or .tar: " answer || answer=""
          fi

          if [ -z "$answer" ]; then
            echo "    nothing given; run 'wm-login vpn' once you have the profile." >&2
            return 0
          fi

          if ! "$pritunl_client" add "$answer"; then
            echo "    'pritunl-client add' failed. Open Pritunl.app once so its" >&2
            echo "    service is running, then run 'wm-login vpn' again." >&2
            return 1
          fi
          echo "    added. Connect it from the Pritunl app."
        }
      ''}

      if [ "$what" = aws ] || [ "$what" = all ]; then
        # The [default] section of ~/.aws/config carries the SSO portal and
        # nothing else, so a login against it is a login for every profile.
        echo "==> AWS SSO (${cfg.aws.ssoStartUrl})"
        aws sso login
      fi

      ${lib.optionalString cfg.gcp.enable ''
        if [ "$what" = gcp ] || [ "$what" = all ]; then
          echo "==> Google Cloud (${cfg.email}, project ${cfg.gcp.project})"
          gcloud auth login ${lib.escapeShellArg cfg.email}
          # Application Default Credentials: what SDKs and Terraform use, as
          # opposed to the gcloud CLI itself. A separate consent screen.
          gcloud auth application-default login
          gcloud auth application-default set-quota-project ${lib.escapeShellArg cfg.gcp.project}
        fi
      ''}

      ${lib.optionalString cfg.vpn.enable ''
        if [ "$what" = vpn ] || [ "$what" = all ]; then
          echo "==> Pritunl VPN (${cfg.vpn.url})"
          vpn_profile
        fi
      ''}
    '';
  };

  profileModule = { ... }: {
    options = {
      account = lib.mkOption {
        type = lib.types.str;
        example = "prod";
        description = "Key into `mine.work.wemaintain.aws.accounts`.";
      };
      role = lib.mkOption {
        type = lib.types.str;
        example = "BackendFullAccess";
        description = "The IAM Identity Center permission set, as `sso_role_name`.";
      };
    };
  };

  databaseModule = { name, ... }: {
    options = {
      host = lib.mkOption {
        type = lib.types.str;
        example = "wemaintain-pgsql-staging.cdtgkxemrw9j.eu-west-1.rds.amazonaws.com";
        description = "RDS endpoint.";
      };
      port = lib.mkOption {
        type = lib.types.port;
        default = 5432;
        description = "Port. Part of what the IAM token is minted for.";
      };
      database = lib.mkOption {
        type = lib.types.str;
        default = "postgres";
        description = "Database name, for the JDBC URL and for `PGDATABASE`.";
      };
      user = lib.mkOption {
        type = lib.types.str;
        example = "backend_dev";
        description = ''
          Database user. Must have `rds_iam` and be granted `rds-db:connect`
          to the role behind `awsProfile`; that pairing is the access level.
        '';
      };
      awsProfile = lib.mkOption {
        type = lib.types.str;
        example = "prod:back";
        description = ''
          Profile (a key of `mine.work.wemaintain.aws.profiles`) whose role
          mints the IAM token.
        '';
      };
      region = lib.mkOption {
        type = lib.types.str;
        default = cfg.aws.region;
        defaultText = lib.literalMD "`mine.work.wemaintain.aws.region`";
        description = "Region the token is minted in. Must match the endpoint's.";
      };
      shellFunction = lib.mkOption {
        type = lib.types.nullOr lib.types.str;
        default = null;
        example = "withPg";
        description = ''
          Name of the zsh function to generate for this database, or null for
          a DataGrip-only entry. `<name> <command>` runs the command with
          DB_*, POSTGRES_* and PG* set to a fresh IAM token.
        '';
      };
      datagrip = {
        enable = lib.mkOption {
          type = lib.types.bool;
          default = true;
          description = ''
            Whether to declare a `mine.programs.datagrip.datasources` entry
            for this database. Only has an effect when
            `mine.programs.datagrip.enable` is on.
          '';
        };
        name = lib.mkOption {
          type = lib.types.str;
          default = "[${lib.toUpper name}] PG";
          defaultText = lib.literalMD "`\"[<NAME>] PG\"`";
          description = ''
            Datasource name in DataGrip. Its uuid, and so the IDE's local
            state for it, is derived from this, so keep it stable.
          '';
        };
      };
    };
  };
in
{
  # `mine.work.wemaintain.enable` is declared in modules/options.nix, with the
  # rest of the opt-in flags. Only the schema lives here.
  options.mine.work.wemaintain = {
    email = lib.mkOption {
      type = lib.types.str;
      example = "ada@wemaintain.com";
      description = ''
        Your WeMaintain Google account. Distinct from `mine.user.email`, which
        is for commit authorship and may well be a personal address. Used as
        the gcloud account.
      '';
    };

    aws = {
      enable = lib.mkOption {
        type = lib.types.bool;
        default = true;
        description = "Manage ~/.aws/config, the RDS CA bundle and the `aws` CLI.";
      };

      ssoStartUrl = lib.mkOption {
        type = lib.types.str;
        default = "https://wemaintainv2.awsapps.com/start";
        description = "IAM Identity Center portal.";
      };

      ssoRegion = lib.mkOption {
        type = lib.types.str;
        default = "eu-west-1";
        description = "Region IAM Identity Center is deployed in.";
      };

      region = lib.mkOption {
        type = lib.types.str;
        default = "eu-west-1";
        description = "Default region for every profile, and for RDS tokens.";
      };

      accounts = lib.mkOption {
        type = lib.types.attrsOf lib.types.str;
        default = { };
        example = { prod = "123456789012"; };
        description = ''
          AWS account ids by short name. The organisation's accounts are
          declared by this module; a host adds to them.
        '';
      };

      profiles = lib.mkOption {
        type = lib.types.attrsOf (lib.types.submodule profileModule);
        default = { };
        example = { "prod:back" = { account = "prod"; role = "BackendFullAccess"; }; };
        description = ''
          Profiles written to ~/.aws/config, named as `--profile` takes them.
          The organisation's standard set is declared by this module; a host
          adds to it, or overrides a field with `lib.mkForce`.
        '';
      };
    };

    databases = lib.mkOption {
      type = lib.types.attrsOf (lib.types.submodule databaseModule);
      default = { };
      description = ''
        RDS databases reached over IAM auth. Each one becomes a shell helper
        (when `shellFunction` is set) and a DataGrip datasource (when
        `datagrip.enable` is), from the one declaration. The standard ones
        are declared by this module; a host adds to them.
      '';
    };

    gcp = {
      enable = lib.mkOption {
        type = lib.types.bool;
        default = true;
        description = "Install `gcloud` and point its active configuration at the project below.";
      };

      project = lib.mkOption {
        type = lib.types.str;
        default = "data-stack-389913";
        description = "Default gcloud project, and the ADC quota project.";
      };
    };

    vpn = {
      enable = lib.mkOption {
        type = lib.types.bool;
        default = true;
        description = ''
          Install the Pritunl cask and give `wm-login` a `vpn` step that mints
          this Mac's VPN profile from the server below.
        '';
      };

      url = lib.mkOption {
        type = lib.types.str;
        default = "https://vpn.wemaintain.io/login";
        description = ''
          The Pritunl server's login page, opened in the browser by
          `wm-login vpn`. It is behind WeMaintain SSO, which is why the profile
          cannot be minted from the CLI.
        '';
      };
    };
  };

  config = lib.mkIf cfg.enable {
    # The organisation, as it stands. Every leaf is `mkDefault` so a host can
    # override one field without restating the rest, and attribute sets merge,
    # so adding a profile or a database is one entry in the host file.
    mine.work.wemaintain.aws.accounts = lib.mapAttrs (_: lib.mkDefault) {
      management = "134801206455";
      # Workload OU
      prod = "637690252147";
      staging = "386096769601";
      # Sandbox OU
      blue = "809773282616";
      # Security OU
      audit = "867545114762";
      log = "983126921565";
    };

    mine.work.wemaintain.aws.profiles =
      let
        profile = account: role: { account = lib.mkDefault account; role = lib.mkDefault role; };
      in
      {
        "management:admin" = profile "management" "AWSAdministratorAccess";

        "prod:admin" = profile "prod" "AWSAdministratorAccess";
        "prod:view" = profile "prod" "AWSReadOnlyAccess";
        "prod:sudo" = profile "prod" "AWSPowerUserAccess";
        "prod:ioth" = profile "prod" "IoTHardwareFullAccess";
        # sic: the permission set is spelled this way upstream.
        "prod:iots" = profile "prod" "IoTSofwareFullAccess";
        "prod:ds" = profile "prod" "DataScientistFullAccess";
        "prod:back" = profile "prod" "BackendFullAccess";
        "prod:mobile" = profile "prod" "MobileFullAccess";
        "prod:front" = profile "prod" "FrontFullAccess";

        "staging:admin" = profile "staging" "AWSAdministratorAccess";
        "staging:sudo" = profile "staging" "AWSPowerUserAccess";

        "blue:admin" = profile "blue" "AWSAdministratorAccess";
        "blue:sudo" = profile "blue" "AWSPowerUserAccess";

        "audit:admin" = profile "audit" "AWSAdministratorAccess";
        "log:admin" = profile "log" "AWSAdministratorAccess";
      };

    # Both databases live in the prod account, staging included, which is why
    # the staging helper authenticates with a `prod:*` profile.
    mine.work.wemaintain.databases =
      let
        rds = env: "wemaintain-pgsql-${env}.cdtgkxemrw9j.eu-west-1.rds.amazonaws.com";
      in
      {
        staging = {
          host = lib.mkDefault (rds "staging");
          user = lib.mkDefault "backend_dev";
          awsProfile = lib.mkDefault "prod:back";
          shellFunction = lib.mkDefault "withPg";
          datagrip.name = lib.mkDefault "[STAGING] PG";
        };
        prod = {
          host = lib.mkDefault (rds "prod");
          user = lib.mkDefault "backend_dev";
          awsProfile = lib.mkDefault "prod:sudo";
          shellFunction = lib.mkDefault "withPgProd";
          datagrip.name = lib.mkDefault "[PROD] PG";
        };
        # Write access to production. DataGrip only, on purpose: a shell
        # helper for it would be one tab-completion away from `withPgProd`.
        prod-write = {
          host = lib.mkDefault (rds "prod");
          user = lib.mkDefault "wmadmin";
          awsProfile = lib.mkDefault "prod:sudo";
          datagrip.name = lib.mkDefault "DANGER WRITE PG PROD";
        };
      };

    assertions =
      [
        {
          assertion = cfg.databases == { } || cfg.aws.enable;
          message = ''
            mine.work.wemaintain.databases needs mine.work.wemaintain.aws.enable:
            the helpers mint RDS IAM tokens with the `aws` CLI and the profiles
            this module writes.
          '';
        }
      ]
      ++ lib.mapAttrsToList
        (name: p: {
          assertion = cfg.aws.accounts ? ${p.account};
          message = ''
            mine.work.wemaintain.aws.profiles."${name}" refers to account
            "${p.account}", which is not in mine.work.wemaintain.aws.accounts.
          '';
        })
        cfg.aws.profiles
      ++ lib.mapAttrsToList
        (name: db: {
          assertion = cfg.aws.profiles ? ${db.awsProfile};
          message = ''
            mine.work.wemaintain.databases.${name} uses profile
            "${db.awsProfile}", which is not in mine.work.wemaintain.aws.profiles.
          '';
        })
        cfg.databases;

    # The CLIs are here rather than in modules/packages.nix because a fork that
    # does not work here has no use for them, and `wm-login` is the one
    # command to remember on a new machine.
    environment.systemPackages =
      [ wm-login ]
      ++ lib.optional cfg.aws.enable pkgs.awscli2
      ++ lib.optional cfg.gcp.enable pkgs.google-cloud-sdk;

    # The cask, not as a preference but as this module's implementation, the way
    # modules/desktop/betterdisplay declares its own: `wm-login vpn` runs a
    # binary inside /Applications/Pritunl.app. It used to be a bare entry in the
    # host's cask list, where it looked like a personal choice; the VPN it
    # reaches is a WeMaintain one, so it belongs behind this flag (#32).
    homebrew.casks = lib.optional cfg.vpn.enable "pritunl";

    # DataGrip sees the same databases, if it is enabled at all. The datagrip
    # module ignores this when it is off, so nothing is gated here.
    mine.programs.datagrip.datasources = lib.mapAttrs'
      (_: db: lib.nameValuePair db.datagrip.name {
        driver = "postgresql";
        url = "jdbc:postgresql://${db.host}:${toString db.port}/${db.database}";
        userName = db.user;
        awsProfile = db.awsProfile;
        awsRegion = db.region;
      })
      (lib.filterAttrs (_: db: db.datagrip.enable) cfg.databases);

    # /etc/zshenv is fought over by two other tools:
    #   - tech.bastion.aiproxy (Bastion, the endpoint agent WeMaintain deploys)
    #     appends its HTTPS_PROXY / NODE_EXTRA_CA_CERTS exports
    #   - the Determinate installer prepends its "set up Nix on SSH" block
    # Either one replaces nix-darwin's symlink with a regular file, and etcChecks
    # then aborts the whole activation with "Unexpected files in /etc".
    #
    # Both tools also write to /etc/zshenv.local, which nix-darwin sources on
    # every shell and never manages, so the copy in /etc/zshenv is pure
    # duplication and nothing is lost by resetting it. Scoped to this one file
    # on purpose — a general /etc auto-heal would silently discard changes that
    # aren't mirrored anywhere. The .drifted copy is kept for inspection.
    #
    # preActivation runs before etcChecks (see nix-darwin's
    # activation-scripts.nix). This lived in hosts/common/darwin.nix until #8;
    # it is here because aiproxy is a work tool, not something every fork
    # of this repo has fighting over its /etc.
    system.activationScripts.preActivation.text = ''
      if [ -e /etc/zshenv ] && [ "$(readlink /etc/zshenv)" != "/etc/static/zshenv" ]; then
        echo "[nix-darwin] /etc/zshenv drifted, moving it to /etc/zshenv.drifted" >&2
        mv -f /etc/zshenv /etc/zshenv.drifted
      fi
    '';

    home-manager.users.${user} = { lib, ... }: lib.mkMerge [
      (lib.mkIf cfg.aws.enable {
        # Symlinks into the store, so `aws configure` cannot write them. That
        # is the point: the config is the declaration above. The SSO token
        # cache (~/.aws/sso) and CLI cache (~/.aws/cli) are untouched.
        home.file.".aws/config".text = awsConfig;
        home.file.".aws/rds-ca-cert.pem".source = ./rds-global-bundle.pem;

        programs.zsh.initContent = lib.mkIf (shellDatabases != [ ]) (
          "# WeMaintain RDS helpers, generated by modules/work/wemaintain.\n"
          + lib.concatMapStringsSep "\n" shellFunction shellDatabases
        );
      })

      (lib.mkIf cfg.gcp.enable {
        # gcloud keeps its configuration in files it rewrites itself, so this
        # is `gcloud config set` at activation rather than a store symlink it
        # could not write to. Idempotent, and local: nothing here needs a
        # login. `wm-login` does the part that does.
        # `gcloud config set core/project` looks the project up over the
        # network with whatever credentials are on disk, and refreshes them
        # first. With an expired token that is "cannot prompt during
        # non-interactive execution", a non-zero exit, and nix-darwin's
        # `set -e` activation dying one line before it links
        # /run/current-system: the generation is built, home files are in
        # place, and nothing new is on PATH. So: never load credentials for
        # this (the lookup then merely warns, silenced by --verbosity=error),
        # and do not call `set` at all when `get`, which is local, already
        # answers what is wanted.
        home.activation.wemaintainGcloud = lib.hm.dag.entryAfter [ "writeBoundary" ] ''
          export CLOUDSDK_CORE_DISABLE_PROMPTS=1
          export CLOUDSDK_AUTH_DISABLE_CREDENTIALS=true
          gcloud=${pkgs.google-cloud-sdk}/bin/gcloud
          set_if_differs() {
            if [ "$("$gcloud" config get "$1" --verbosity=error 2>/dev/null || true)" != "$2" ]; then
              $DRY_RUN_CMD "$gcloud" config set "$1" "$2" --quiet --verbosity=error >/dev/null
            fi
          }
          set_if_differs core/project ${lib.escapeShellArg cfg.gcp.project}
          set_if_differs core/account ${lib.escapeShellArg cfg.email}
        '';
      })
    ];
  };
}
